### ISSUE TITLE
Referentie-implementatie in definition of done ?

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen#10]
Melvin vraagt zich n.a.v. de definition_of_done af of een referentieimplementatie nog relevant is. 

Zijn stelling is de volgende :

Ik denk meer dat het team zichzelf gijzelt, want nu kan je niet zeggen dat je 'done' bent totdat er een referentie implementatie is. Volgens mij is de test implementatie van processFive wat anders dan een referentie implementatie. Maar ik vind het prima om het zo te laten

Aan de andere kant stelt VNG Realisatie dat er bij een standaard een referentie-implementatie beschikbaar moet zijn om de standaard in beheer te nemen. 

Hoe gaan we daar binnen Haal-Centraal mee om.

![image](https://user-images.githubusercontent.com/18071357/96244288-26826680-0fa6-11eb-9a5e-fb8f7bfdaf6d.png)

**Comment by fsamwel** [comment]
> Aan de andere kant stelt VNG Realisatie dat er bij een standaard een referentie-implementatie beschikbaar moet zijn om de standaard in beheer te nemen.

Volgens mij levert Haal Centraal geen standaard, maar werkende API's. Dus naar mijn idee kan de referentie-implementatie eis eruit.

**Comment by melsk-r** [comment]
Als ik het goed begrepen heb wordt er bij de ZGW API standaarden niet alleen een RI voor de provider applicatie geleverd maar ook een voor de consumer applicatie. Ik kan me er wat bij voorstellen dat een RI voor een provider applicatie niet van toepassing is voor Haal Centraal API's maar volgens mij geldt dat niet voor een RI voor een consumer applicatie.

**Comment by fsamwel** [comment]
Dan zou ik liever goede client SDK's hebben dan een client referentie implementatie.

**Comment by JohanBoer** [comment]
> Volgens mij levert Haal Centraal geen standaard, maar werkende API's. Dus naar mijn idee kan de referentie-implementatie eis eruit

Er zal dan toch een test-API moeten komen waar consumers de werking kunnen toetsen voordat ze tegen productie aan gaan praten lijkt mij. Dat hoeft voor mij geen referentie-implementatie te heten, maar laten we het sandbox noemen. Minder zware eisen dan aan een referentie-implementatie, maar niet gewoon weglaten in mijn beleving. 

Cliennt SDK's zijn een sowieso goed idee, maar met een cliet referentie-implementatie heb je in ieder geval de implemnteerbaarheid van de standaard volledig beproefd. 

Als het uiteindelijk de bedoeling is dat deze specificaties door VNG-Realisatie worden beheerd zal toch aan de definition_of_done van VNG-Realisatie voldaan moeten worden. 
Alternatief is deze uitzonderingspositie voor Haal Centraal besproken en vastgelegd wordt. Volgens mij gaan wij daar uiteindelijk niet over, maar zal dit door programma-management en management VNG-Realisatie moeten worden besproken.

**Comment by fsamwel** [comment]
@JohanBoer goede discussie. onderliggende punt is de scope van (de definition of done voor) Haal Centraal.
1. Alleen het ontwerpen van de API (zoals bij BRP en HR)
2. Bouwen en direct in productie brengen van de API (zoals bij BAG en BRK)

In het eerste geval is een sandbox/referentie implementatie wellicht nuttig om de implementeerbaarheid te testen. Maar een referentie-implementatie of test implementatie denk ik niet. We zitten dan immers te wachten op daadwerkelijke implementatie. 

In het tweede geval in de DoD veel breder. Dan gaat het om een testomgeving, proces om op de test- en productieomgeving aan te sluiten, beheer geregeld, enz. Maar dan komen we snel op of over de grenzen van wat de scope (concern) van het Haal Centraal project is.

**Comment by CathyDingemanse** [comment]
Referentie implementaties zijn nooit in scope geweest van Haal Centraal. Wij leveren API's, geïmplementeerd en wel. 
Dat de referentie implementatie onderdeel uit maakt van de definition of done, komt omdat RvIG niet in beeld was voor realisatie van onze eerste API. Omdat dit niet langer het geval is, zie ik geen reden om de referentie implementatie te handhaven als onderdeel van de definition of done. 

Ik stel voor om ipv de referentie-implementatie de API implementatie door een landelijke aanbieder op te nemen als onderdeel van de definition of done.

**Comment by CathyDingemanse** [comment]
> Als het uiteindelijk de bedoeling is dat deze specificaties door VNG-Realisatie worden beheerd zal toch aan de definition_of_done van VNG-Realisatie voldaan moeten worden.
> Alternatief is deze uitzonderingspositie voor Haal Centraal besproken en vastgelegd wordt. Volgens mij gaan wij daar uiteindelijk niet over, maar zal dit door programma-management en management VNG-Realisatie moeten worden besproken.

Wat bedoel je hiermee?
