### ISSUE TITLE
Reden zit niet in de InOnderzoek van Ontbindinghuwelijk_Partnerschap maar wel in het hoofd object

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen#17]
# Impediment

In de Bevraging Historie specs kan onder Ontbindinghuwelijk_Partnerschap een attribuut genaamd 'Reden' vinden, maar deze is niet terug te vinden bij OntbindingHuwelijkInOnderzoek. Is deze vergeten weg te voegen aan het inonderzoek object of vergeten weg te halen bij het andere object?

> Ontbindinghuwelijk_Partnerschap:
      type: "object"
      description: ""
      properties:
        datum:
          $ref: "#/components/schemas/Datum_onvolledig"
        land:
          $ref: "#/components/schemas/Waardetabel"
        plaats:
          $ref: "#/components/schemas/Waardetabel"
        reden:
          $ref: "#/components/schemas/Waardetabel"
        inOnderzoek:
          $ref: "#/components/schemas/OntbindingHuwelijkInOnderzoek"
    OntbindingHuwelijkInOnderzoek:
      type: "object"
      description: "<body><p>Indicators over het in onderzoek zijn van gegevens over\
        \ de aangaan van het huwelijk van de INGESCHREVEN PERSOON.</p><p>Zie de <a>functionele\
        \ specificaties</a> </p></body>"
      properties:
        datum:
          type: "boolean"
          title: "datum"
          description: "<body><p>Indicator die aangeeft of het corresponderende gegeven\
            \ voor deze persoon in onderzoek is.</p></body>"
        land:
          type: "boolean"
          title: "land"
          description: "<body><p>Indicator die aangeeft of het corresponderende gegeven\
            \ voor deze persoon in onderzoek is.</p></body>"
        plaats:
          type: "boolean"
          title: "plaats"
          description: "<body><p>Indicator die aangeeft of het corresponderende gegeven\
            \ voor deze persoon in onderzoek is.</p></body>"
        datumEindeOnderzoek:
          $ref: "#/components/schemas/Datum_onvolledig"
        datumIngangOnderzoek:
          $ref: "#/components/schemas/Datum_onvolledig"

**Comment by JohanBoer** [comment]
Ik heb n.a.v. deze reactie van Gert Jan de reden toegevoegd aan OntbindingHuwelijkInOnderzoek.

@CathyDingemanse @fsamwel 

Zijn jullie het daar mee eens ?
