### ISSUE TITLE
descriptions

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen#22]
- [x] title: BRP historie bevragen: 
- [x] Description: API voor het zoeken en raadplegen van historische verblijfplaatsen, partners, nationaliteiten en verblijfstitels uit de BRP (inclusief de RNI).

- [x] Tag: description idem als API titel

Endpoints: 
- [x] /ingeschrevenpersonen/{burgerservicenummer}/verblijfplaatshistorie
Zoek de verblijfplaatshistorie van een persoon op de opgegeven peildatum of binnen de opgegeven periode verbleef. Als je geen peildatum of periode opgeeft, krijg je alle verblijfplaatsen terug. Het meest actuele adres staat bovenaan.

- [x] /ingeschrevenpersonen/{burgerservicenummer}/partnerhistorie
Zoek de partnerhistorie van een persoon op de opgegeven peildatum of binnen de opgegeven periode. Als je geen peildatum of periode opgeeft, krijg je alle partners terug waarmee een partnerschap is aangegaan of een huwelijk is gesloten.  

- [x] /ingeschrevenpersonen/{burgerservicenummer}/verblijfstitelhistorie
Zoek de verblijfstitelhistorie van een persoon op de opgegeven peildatum of binnen de opgegeven periode. Als je geen peildatum of periode opgeeft, krijg je alle verblijfstitels van de persoon terug. De meest actuele verblijfstitel staat bovenaan.

- [x] /ingeschrevenpersonen/{burgerservicenummer}/nationaliteithistorie
Zoek de nationaliteithistorie van een persoon op de opgegeven peildatum of binnen de opgegeven periode. Als je geen peildatum of periode opgeeft, krijg je alle nationaliteiten van de persoon terug. De meest actuele nationaliteit staat bovenaan.

**Comment by CathyDingemanse** [comment]
Nationaliteithistorie:
- description: Gegevens over de (historische) nationaliteiten van de persoon.
  properties:
    geheimhoudingPersoonsgegevens: Gegevens mogen niet worden verstrekt aan derden / maatschappelijke instellingen.
    indicatieNationaliteitBeeindigd: Geeft aan dat de nationaliteit beëindigd is

Verblijfplaatshistorie: 
- description: Gegevens over de (historische) verblijfplaatsen of de woonlocaties van de persoon.
  properties:
    geheimhoudingPersoonsgegevens: Gegevens mogen niet worden verstrekt aan derden / maatschappelijke instellingen.


Partnerhistorie:
- description: Gegevens over (historische) huwelijken en/of geregistreerd partnerschappen van de persoon.
    ontbindingHuwelijkPartnerschap: 
      properties:
        indicatieHuwelijkPartnerschapBeeindigd: 
          type: boolean
          description: |
                        Geeft aan dat het huwelijk is ontbonden of het partnerschap is be�indigd.
OntbindingHuwelijkInOnderzoek:
- description: Geeft aan dat de ontbinding van het huwelijk of de beëindiging van het partnerschap in onderzoek is.


Verblijfstitelhistorie:
- description: Gegevens over de (historische) verblijfsrechtelijke status van de persoon.
datumEinde: Datum waarop de verblijfstitel niet meer geldig is.
datumIngang: Datum waarop de verblijfstitel ingaat.
aanduiding : Verblijfstiteltabel die aangeeft over welke verblijfsrechtelijke status de persoon beschikt.
Zou je deze descriptions bij actueel ook willen veranderen? (Nieuwe minor versie?)

  properties:
   geheimhoudingPersoonsgegevens: Gegevens mogen niet worden verstrekt aan derden / maatschappelijke instellingen.

**Comment by JohanBoer** [comment]
> * Zou je deze descriptions bij actueel ook willen veranderen? (Nieuwe minor versie?)

https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/687#issue-729584636

aangemeakt en op de backlog van BRP-bevragen gezet.

**Comment by CathyDingemanse** [comment]
Laatste check:

 /ingeschrevenpersonen/{burgerservicenummer}/verblijfplaatshistorie
Zoek de verblijfplaatshistorie van een persoon op de opgegeven peildatum of binnen de opgegeven periode. Als je geen peildatum of periode opgeeft, krijg je alle verblijfplaatsen terug. Het meest actuele adres staat bovenaan.
