### ISSUE TITLE
Property in Verblijfplaatshistorie komt niet overeen met parameter. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen#5]
We hebben voor het zoeken in de historie de parameters datumVan en datumTotEnMet gedefinieerd. 
In de Verblijfplaatshistorie komen nu diverse datums voor, 
- datumIngangGeldigheid
- datumAanvangAdreshouding
- datumTot

Het is toch best practice om de parameters ook op te nemen in de response indien mogelijk ?
Daarnaast staat in (de oude) design decision dat het burgerservicenummer onderdeel is van de response. 
Dat burgerservicenummer zit natuurlijk wel in de self-link van de response. Is dat dan afdoende ?

**Comment by JohanBoer** [comment]
Deze tekst stond in de design decisions. 
Gaarne voor alle resources en endpoints een keer doornemen.

**Er kan gekozen worden om de status op peildatum te raadplegen met de queryparameter peildatum.
Er kan gekozen worden de historische voorkomens te raadplegen binnen een periode met queryparameters datumVan en datumTotEnMet.

Het antwoordbericht van /verblijfplaatsen bevat het property burgerservicenummer van de ingeschreven natuurlijk persoon, plus \_links en \_embedded met de historische voorkomens van de verblijfplaats van de persoon. Hierin zit ook de property datumIngangGeldigheid.
Het antwoordbericht van /verblijfstitels bevat de historische voorkomens van de verblijfstitel van de ingeschreven persoon en de properties geldigVan en geldigTotEnMet.
Het antwoordbericht van /partners bevat het property burgerservicenummer van de ingeschreven natuurlijk persoon, plus de historische voorkomens van partner-relaties (huwelijken of geregistreerd partnerschappen). Hierin zitten ook de geldigVan en geldigTotEnMet.
Het antwoordbericht van /bewoningen bevat de lijst gevonden adressen, met voor elk adres de bewoners met elk de properties geldigVan en geldigTotEnMet.**

**Comment by fsamwel** [comment]
> Het is toch best practice om de parameters ook op te nemen in de response indien mogelijk ?

Ik denk dat de best practice (en NL API strategie regel) is dat query parameters dezelfde naam hebben als het property in de response waar ze op filteren. Dat doen we hopelijk ook altijd.

Alleen bij historie zijn datumVan en datumTotEnMet geen "normale" parameters, want ze filteren niet op het gelijk zijn van waarde in de resource. Daarom hebben we geen queryparamter "datumAanvangAdreshouding", maar "datumVan".
We hadden ervoor kunnen kiezen om hier de queryparameter "datumAanvangAdreshoudingVan" te gebruiken. Dat hebben we niet gedaan, want de functionaliteit zou daarvan anders worden. We zoeken met datumVan niet naar resources waarbij datumAanvangAdreshouding op of na datumVan ligt. Met datumVan zoeken we naar verblijf waarbij datumAanvangAdreshouding op of **voor** datumVan ligt én **datumTot** na datumVan.
Ook was een overweging dat hiermee alle historische API's/endpoints op dezelfde manier werken wat betreft het filteren op periode.

> Daarnaast staat in (de oude) design decision dat het burgerservicenummer onderdeel is van de response.
Dat burgerservicenummer zit natuurlijk wel in de self-link van de response. Is dat dan afdoende ?

Naar mijn idee is dit afdoende. Alleen klopt de design decision niet, want die zegt iets anders.

**Comment by JohanBoer** [comment]
> Met datumVan zoeken we naar verblijf waarbij datumAanvangAdreshouding op of **voor** datumVan ligt én **datumTot** na datumVan.

Duidelijk Frank, was hem even kwijt. Denk dat bovenstaande zin bedoeld is als : 

Met datumVan zoeken we naar verblijf waarbij datumAanvangAdreshouding op of **voor** **_datumTotEnMet_** ligt én **datumTot** na datumVan.

Ik sluit 'm.

**Comment by melsk-r** [comment]
> > Daarnaast staat in (de oude) design decision dat het burgerservicenummer onderdeel is van de response.
> > Dat burgerservicenummer zit natuurlijk wel in de self-link van de response. Is dat dan afdoende ?
> 
> Naar mijn idee is dit afdoende. Alleen klopt de design decision niet, want die zegt iets anders.

Welke Design Decision betreft dit en is er een issue aangemaakt om dit te verbeteren?

**Comment by JohanBoer** [comment]
> Welke Design Decision betreft dit en is er een issue aangemaakt om dit te verbeteren?

Dit gaat om de design_decisions van BRP-historie. Die staat nu in een pull request in deze repository klaar. Daarin worden dee wijzigingen aangebracht. 
Als dit afdoende antwoord is voor jou, sluit jij de issue dan weer, Robert ?

**Comment by melsk-r** [comment]
Ah, de Design Decision van de BRP-historie. Dat is duidelijker. Ik dacht even dat je op een specifieke Design Decision item in de Design Decision in HaalCentraal common doelde.
