### ISSUE TITLE
Properties m.b.t historie zijn niet consistent. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen#8]
Nu zijn de properties die in de resources zitten die te maken hebben met historie volgens mij niet consistent. 
We hebben de volgende situatie (op basis van de recente aanpassing van de design_decisions) : 

- Het antwoordbericht van /verblijfplaatshistorie bevat \_links en \_embedded met de historische voorkomens van de verblijfplaats van de persoon. Hierin zitten ook de properties datumIngangGeldigheid en datumTot. 
- Het antwoordbericht van /verblijfstitelhistorie bevat de historische voorkomens van de verblijfstitel van de ingeschreven persoon en de properties datumEinde en datumIngang.
- Het antwoordbericht van /partnerhistorie bevat de historische voorkomens van partner-relaties (huwelijken of geregistreerd partnerschappen). Hierin zit in de groep aangaanHuwelijkPartnerschap een datum en in de groep ontbindingHuwelijkPartnerschap een datum.
- Het antwoordbericht van /nationaliteithistorie bevat de historische nationaliteiten die voor een persoon geregistreerd zijn. Hierin zitten de properties datumIngangGeldigheid en datumEindeGeldigheid. 

Dat Partnerhistorie afwijkt van de naamgevingsconventie snap ik. 

- Moet het bij verblijfplaatsHistorie niet een datumIngang en datumEinde worden ?
- Hetzelfde geldt voor nationaliteitHistorie. 

In de description van verblijfstitelHistorie ontbreekt de toeloichting op datumTot.

**Comment by fsamwel** [comment]
> Moet het bij verblijfplaatsHistorie niet een datumIngang en datumEinde worden ?

Naar mijn idee niet. Zie design decisions:
> ### DD5.14 Gebruik bestaande functionele gegevens voor begin- en einddatum
> Wanneer er voor een begindatum of einddatum al een functioneel gegeven bestaat, gebruiken we die. Denk aan datumOntbindingHuwelijk of datumAanvangAdreshouding.

> ### DD5.15 Definieer 'datumTot' indien er behoefte is aan een einddatum maar afwezig in het informatiemodel
> Wanneer een functioneel gegeven in het informatiemodel voor einddatum afwezig is terwijl daar wel behoefte aan is (omdat historie getoond wordt) gebruiken we "datumTot". Bijvoorbeeld in de BRP wordt alleen de begindatum van een verblijfplaats geregistreerd en geen einddatum. Daar is datumTot dus de datumAanvang van de volgende verblijfplaats.

In alle 4 de historie resources is er in het informatiemodel een "functioneel" gegeven voor zowel begindatum als einddatum, behalve de einddatum voor verblijfplaatsen.

**Comment by JohanBoer** [comment]
Bij nationaliteit --> en datumTot

Rest blijft wat het is.
