### ISSUE TITLE
Tekst uit design decision ergens anders plaatsen

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen#9]
In de design-decision staat nu een stukje functionele beschrijving van de historie endpoints onder het kopje:

## Opvragen van historie kan via specifieke endpoints

Dit stukje tekst is nu achterhaald als design decision, maar zou opgenomen kunnen worden in de Readme.md of als description van de API.

Wat heeft de voorkeur

**Comment by melsk-r** [comment]
Als ik zo de Readme.md van de BRK bevragen, BAG bevragen en BRP bevragen API's lees dan vind ik dat het door jou bedoelde stukje tekst daar niet in thuis hoort. Ik zou het dus in de description van de API plaatsen. Ik vraag me alleen af welk document dat dan precies zou moeten zijn. Ik zie bij de 3 genoemde API's diverse documenten maar ik zie geen document waaruit ik direct de conclusie trek dat dat de description zou moeten zijn.

**Comment by fsamwel** [comment]
of gewoon weglaten? Is volgens mij inderdaad achterhaald. De specificaties en features over historie zijn actueler en duidelijker.

**Comment by JohanBoer** [comment]
> of gewoon weglaten? Is volgens mij inderdaad achterhaald. De specificaties en features over historie zijn actueler en duidelijker.

Eens. Weggehaald.
